/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('experiences').del()
  await knex('experiences').insert([
    {id: 1, poste: 'Lead Développeur Fullstack', esn: '', enterprise: 'Bemyapp', from: '2020-11-01', to: '2022-12-01', stillInPost: false, logo: 'bemyapp.png', city: 'Nantes', country: '', tools: 'Vue.js, Node.js, GraphQL, MongoDB, Redis, Git', order: '1', page: '1', description: 'Développement et maintenance de l\'application (code, infra). Participation aux choix techniques structurants et à leur intégration dans la roadmap. Conception technique, accompagnement de la réalisation et de la mise en production d\'une fonctionnalité majeure. 4 Personnes sur un an. Développement, en binôme avec un architecte AWS, de l\'agrégation des  données fonctionnelles et de leurs mises à disposition aux clients dans un dashboard. Restructuration et optimisation de la gamification sur la plateforme', resume: 5},
    {id: 2, poste: 'Développeur Fullstack', esn: 'Netapsys/Sodifrance', enterprise: 'Miriad', from: '2019-01-01', to: '2020-11-01', stillInPost: false, logo: 'miriad.png', city: 'Nantes', country: '', tools: 'Java 8, Angular 7, PostreSql, ElasticSearch, Git', order: '2', page: '1', description: 'Migration et fusion de deux applications, accompagnées d\'ajout de nombreuses fonctionnalités. En tant que développeur sénior j\'ai eu à accompagner et encadrer les juniors, ainsi qu\'à participer aux étapes de chiffrage et de conception', resume: 5},
    {id: 3, poste: 'Développeur Fullstack', esn: 'Netapsys/Sodifrance', enterprise: 'Icowsoft', from: '2018-03-01', to: '2019-01-01', stillInPost: false, logo: 'icowsoft.png', city: 'Nantes', country: '', tools: 'Vue.js, Node.js, Java 8, AngularJs, Git, Docker, Quasar', order: '3', page: '1', description: 'Développement de nouvelles fonctionnalités pour l\'éditeur de logiciel Icowsoft. Ces fonctionnalités prennent place sur une application web codée en Java/AngularJs et une application mobile codée en VueJs. De nombreux autres modules, codés principalement en NodeJs, orbitent autours des ces deux applcations selon une architecture micro-service.', resume: 5},
    {id: 4, poste: 'Développeur Fullstack', esn: 'SFEIR', enterprise: 'Generali', from: '2017-03-01', to: '2018-02-01', stillInPost: false, logo: 'generali.png', city: 'Nantes', country: '', tools: 'Angular 4, Polymere, Redux, Java 8, Jenkins, Maven, Git, Jira, Spring, Hibernate', order: '4', page: '2', description: 'Développement "from scratch" de l\'application de gestion des flottes  automobiles. Piloté avec la méthodologie Agile et au sein d\'une équipe de développeurs de 5 personnes, j\'étais en charge de mettre en place l\'architecture de la partie Front de l\'application et d\'en moderniser la navigation.', resume: 5},
    {id: 5, poste: 'Développeur Fullstack', esn: 'Groupe OnePoint', enterprise: 'Société Générale', from: '2016-02-01', to: '2017-02-01', stillInPost: false, logo: 'societegenerale.png', city: 'Montréal', country: 'CA', tools: 'Java 7, AngularJs, Maven, Git, Sonar', order: '5', page: '2', description: 'Au sein du pôle technique de la Société Générale en Amérique du Nord, j\'ai participé à la migration d\'une application bancaire sensible, gérant nottament les appels de marge. C\'était donc une des applications critiques de la banque d\'autant qu\'elle était de portée internationale. Pilotée par la méthodologie Scrum, avec des clients de nationalités multiples, nous devions migrer l\'application sur des technologies WEB. Pour ce faire, nous avons utilisé du cloud pour les serveurs, du Java pour la partie Back End et du AngularJS pour la partie Front End', resume: 5},
    {id: 6, poste: 'Roadside Engineer', esn: '', enterprise: 'Sanef ITS', from: '2015-08-01', to: '2016-01-01', stillInPost: false, logo: 'sanef.png', city: 'Vancouver', country: 'CA', tools: '', order: '6', page: '2', description: 'Dans un environnement anglophone, en lien avec l\'organisation gouvernementale, les équipes de sécurité routière et les équipes de développement en France. J\'avais à ma charge la responsabilité de maintenir les installations du nouveau péage Free-Flow en fonctionnement. Cette tâche m\'amenait à réaliser des modifications de code source, de l\'informatique embarquée et de l\'électronique.', resume: 5},
    {id: 7, poste: 'Développeur Java', esn: 'Groupe OnePoint', enterprise: 'SFR', from: '2014-05-01', to: '2015-07-01', stillInPost: false, logo: 'sfr.png', city: 'Nanterre', country: '', tools: 'Java, W4, Jenkins, Mantis, Svn, Perl, PL/SQL, Jira, Maven', order: '7', page: '2', description: 'Membre de la cellule de support niveau 3 du projet de gestion des accès et des services des lignes fixes (téléphone et internet). J\'effectuais la prise en charge et le suivi des tickets utilisateurs. J\'avais également pris part au projet de fusion des SI SFR et Numéricable', resume: 5},
    {id: 8, poste: 'Ingénieur BI', esn: 'Sopra Group', enterprise: 'Maroc Telecom', from: '2013-03-01', to: '2014-04-01', stillInPost: false, logo: 'maroctelecom.png', city: 'La Défense', country: '', tools: 'ETL Infosphere IBM, Oracle 11, Business Object, Shell Unix, PL/SQL, Cvs', order: '8', page: '2', description: 'Maintien et évolution du système décisionnel de Maroc Telecom. J\'étais chargé de corriger les anomalies remontées par le client et de développer des évolutions. Autonome et responsable, j\'étais présent dans l\'ensemble du cycle de vie d\'une évolution. J\'échangeais avec le client pour convenir des spécifications, je réalisais les modifications ainsi que la rédaction des tests unitaires et la mise en production. Le nombre de tickets était conséquent et l\'optimisation de l\'application était la priorité. Ceci était fait en améliorant la configuration de la BDD Oracle et l\'écriture des requêtes SQL.', resume: 5},
  ]);
};