type Experience {
  id: Int,
  poste: String!
  esn: String
  enterprise: String!
  from: Date!
  to: Date
  stillInPost: Boolean
  logo: String
  city: String
  country: String
  description: String
  order: String!
  tools: String
  page: String!
}

input ExperienceInput {
  id: Int,
  poste: String!
  esn: String
  enterprise: String!
  from: Date!
  to: Date
  stillInPost: Boolean
  logo: String
  city: String
  country: String
  description: String
  order: String!
  tools: String
  page: String!
}

type Query {
  experiences(resumeId: Int): [Experience]
}

type Mutation {
  updateExperience(experience: ExperienceInput, resumeId: Int): Experience
  deleteExperience(id: Int): Int
}
