type User {
  id: Int,
  username: String
}

input UserInput {
  id: Int,
  username: String!
}

type Query {
  users: [User!]!
}

type Mutation {
  addUser(user: UserInput): User
  deleteUser(id: Int): Int
}