scalar Date

type User {
  id: Int,
  username: String
  email: String
  telephone: String
  birthdate: Date
  adresse: String
  city: String
}

input UserInput {
  id: Int,
  username: String!
  email: String!
  telephone: String!
  birthdate: Date!
  adresse: String!
  city: String!
}

type Query {
  users: [User!]!
}

type Mutation {
  addUser(user: UserInput): User
  deleteUser(id: Int): Int
}